#ifndef LAB1LLP_COLUMN_TYPES_H
#define LAB1LLP_COLUMN_TYPES_H

enum CellType {
    TABLE_TYPE_INT = 0,
    TABLE_TYPE_BIGINT,
    TABLE_TYPE_VARCHAR,
    TABLE_TYPE_FLOAT,
    TABLE_TYPE_BOOL,
    TABLE_TYPE_EMPTY,
};

#endif //LAB1LLP_COLUMN_TYPES_H
