#ifndef LAB1LLP_TABLE_CONSTS_H
#define LAB1LLP_TABLE_CONSTS_H

#define TABLE_MAX_NAME_LENGTH 100
#define COLUMN_MAX_NAME_LENGTH 50
#define TABLE_MAX_COLUMNS 100
#define MAX_TABLES_COUNT 100

#endif //LAB1LLP_TABLE_CONSTS_H
